# --- MariaDB-Konfiguration ---
# Das Format ist: jdbc:mariadb://<host>:<port>/<datenbankname>
database.url=jdbc:mariadb://fst.selfhost.bz:53306/kontakt

# Datenbank-Benutzername
database.user=kontakt

# Datenbank-Passwort
database.password=kontakt